### ISSUE TITLE
Ender 2.0 unable to build modules that have CRLF line endings

### ISSUE THREAD

**Issue by ryanve** [ender-js/ender-builder#2]
Ender 2.0.3 gives me the error below when I try to do an `ender build` that includes any modules that use CRLF line endings (which applies to [most of mine](https://www.npmjs.org/~ryanve) because I `npm publish` from a Windows machine). The same modules build fine with Ender 1.1. For example

``` sh
$ ender build fm@0.2.1
```

<a href="../blob/de586688b29025f8e423616f07fd0a1d00c1974c/lib/minifiers/uglify.js#L55"><pre><samp>Assembling build...Minify Error: Uglify error</samp></pre></a>

If I go into `node_modules` and manually convert the main and bridge files to Unix (LF) line endings then it builds fine.

I think [this is the problematic line](../blob/de586688b29025f8e423616f07fd0a1d00c1974c/lib/minifiers/uglify.js#L31). Passing the `.orig` property to `UglifyJS.SourceMap` causes the error. Normalizing line endings with `.replace(/\r\n|\r|\n/g, '\n')` did not help there, but if I remove `.orig` or set it to `null` then it builds with no errors.

**Comment by amccollum** [comment]
Is one of the modules you're referring to on GitHub so I can debug this later today?

**Comment by ryanve** [comment]
@amccollum Thanks Andrew. Yes, they're on [github.com/ryanve](https://github.com/ryanve?tab=repositories) (for example [fm](https://github.com/ryanve/fm) or [energy](https://github.com/ryanve/energy)) and they're on [npm](https://npmjs.org/~ryanve) too. See [eol](https://github.com/ryanve/eol) if needed for conversion. I think the clash is with the source map. I wondered if there was a way to opt out of them that I could try.

**Comment by amccollum** [comment]
Ok, I pushed a fix in https://github.com/ender-js/ender-builder/commit/3be805310eee0c3ea2b984d33a891a7fff202d86 and it should be updated in NPM now. Let me know if you're still having issues.

**Comment by ryanve** [comment]
@amccollum Thanks—no errors <b>=)</b> Now at least it builds, but the outputted .js files are getting double spaced for some modules. The affected portions have an extra line under every line. It's no big deal but it must be related. For some modules (e.g. [actual](https://github.com/ryanve/actual)) it double spaces the whole module and in others (e.g. [fm](https://github.com/ryanve/fm)) it double spaces just the [banner comment](https://github.com/ryanve/fm/blob/0.3.1/fm.js#L1-L5) at the top. It may relate to how I [generate those with grunt](https://github.com/ryanve/fm/blob/0.3.1/GruntFile.js#L36-L42).
